import type { Incident } from '../../../services/incidentService';

export const DEMO_INCIDENTS: Incident[] = [
    {
        id: '1',
        title: 'Broken Street Light',
        description: 'Street light flickering and making noise, causing visibility issues at night.',
        latitude: 33.5731,
        longitude: -7.5898,
        address: 'Bd Mohamed V, Casablanca',
        status: 'NEW',
        priority: 'MEDIUM',
        category: { id: 'LIGHTING', name: 'Lighting' },
        reporter: { id: 'u1', email: 'user@example.com', firstName: 'Ahmed', lastName: 'Benali', fullName: 'Ahmed Benali' },
        photos: [],
        commentsCount: 0,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString()
    },
    {
        id: '2',
        title: 'Pothole on Main Road',
        description: 'Large pothole damaging cars near the intersection.',
        latitude: 33.5785,
        longitude: -7.6150,
        address: 'Bd Anfa, Casablanca',
        status: 'IN_PROGRESS',
        priority: 'HIGH',
        category: { id: 'INFRASTRUCTURE', name: 'Roads' },
        reporter: { id: 'u2', email: 'user2@example.com', firstName: 'Sara', lastName: 'Idrissi', fullName: 'Sara Idrissi' },
        photos: [],
        commentsCount: 2,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString()
    },
    {
        id: '3',
        title: 'Uncollected Trash',
        description: 'Garbage piling up for 3 days.',
        latitude: 33.5850,
        longitude: -7.6000,
        address: 'Maarif, Casablanca',
        status: 'NEW',
        priority: 'HIGH',
        category: { id: 'SANITATION', name: 'Trash' },
        reporter: { id: 'u3', email: 'user3@example.com', firstName: 'Karim', lastName: 'Tazi', fullName: 'Karim Tazi' },
        photos: [],
        commentsCount: 1,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString()
    },
    {
        id: '4',
        title: 'Dangerous Intersection',
        description: 'Traffic lights not working properly.',
        latitude: 33.5600,
        longitude: -7.6200,
        address: 'Hay Hassani, Casablanca',
        status: 'ASSIGNED',
        priority: 'HIGH',
        category: { id: 'SAFETY', name: 'Safety' },
        reporter: { id: 'u4', email: 'user4@example.com', firstName: 'Yasmine', lastName: 'Fassi', fullName: 'Yasmine Fassi' },
        photos: [],
        commentsCount: 5,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString()
    },
    {
        id: '5',
        title: 'Fallen Tree Branch',
        description: 'Blocking the sidewalk.',
        latitude: 33.5900,
        longitude: -7.5800,
        address: 'Parc Ligue Arabe, Casablanca',
        status: 'RESOLVED',
        priority: 'LOW',
        category: { id: 'NATURE', name: 'Nature' },
        reporter: { id: 'u5', email: 'user5@example.com', firstName: 'Omar', lastName: 'Lyamani', fullName: 'Omar Lyamani' },
        photos: [],
        commentsCount: 0,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString()
    }
];
