import React from 'react';
import {
    Activity,
    AlertTriangle,
    Ambulance,
    Anchor,
    Archive,
    Armchair,
    ArrowRight,
    Axe,
    Backpack,
    Banknote,
    BarChart,
    Battery,
    Bell,
    Bike,
    Book,
    Box,
    Briefcase,
    Building,
    Bus,
    Calendar,
    Camera,
    Car,
    CheckCircle,
    ChevronDown,
    ChevronLeft,
    ChevronRight,
    ChevronUp,
    Circle,
    Clipboard,
    Clock,
    Cloud,
    Code,
    Cog,
    Compass,
    Copy,
    CreditCard,
    Crop,
    Database,
    Disc,
    DollarSign,
    Download,
    Droplet,
    Edit,
    Edit2,
    Edit3,
    ExternalLink,
    Eye,
    EyeOff,
    File,
    FileMinus,
    FilePlus,
    FileText,
    Filter,
    Flag,
    Folder,
    FolderMinus,
    FolderPlus,
    Gift,
    Globe,
    Grid,
    HardHat,
    Headphones,
    Heart,
    HelpCircle,
    Home,
    Image,
    Inbox,
    Info,
    Key,
    Layers,
    Layout,
    LifeBuoy,
    Lightbulb,
    Link,
    List,
    Loader,
    Lock,
    LogOut,
    Mail,
    Map,
    MapPin,
    Maximize,
    Menu,
    MessageCircle,
    MessageSquare,
    Mic,
    Minimize,
    Minus,
    Monitor,
    Moon,
    MoreHorizontal,
    MoreVertical,
    Move,
    Music,
    Navigation,
    Package,
    Paperclip,
    Pause,
    PauseCircle,
    PenTool,
    Phone,
    PieChart,
    Play,
    PlayCircle,
    Plus,
    PlusCircle,
    Pocket,
    Power,
    Printer,
    Radio,
    RefreshCw,
    Repeat,
    Save,
    Scissors,
    Search,
    Send,
    Server,
    Settings,
    Share,
    Share2,
    Shield,
    ShoppingBag,
    ShoppingCart,
    Shuffle,
    Sidebar,
    SkipBack,
    SkipForward,
    Slack,
    Slash,
    Sliders,
    Smartphone,
    Smile,
    Speaker,
    Square,
    Star,
    StopCircle,
    Sun,
    Sunrise,
    Sunset,
    Tablet,
    Tag,
    Target,
    Terminal,
    Thermometer,
    ThumbsDown,
    ThumbsUp,
    ToggleLeft,
    ToggleRight,
    Trash,
    Trash2,
    Trello,
    TrendingDown,
    TrendingUp,
    Triangle,
    Truck,
    Tv,
    Twitter,
    Type,
    Umbrella,
    Underline,
    Unlock,
    Upload,
    UploadCloud,
    User,
    UserCheck,
    UserMinus,
    UserPlus,
    UserX,
    Users,
    Video,
    VideoOff,
    Voicemail,
    Volume,
    Volume1,
    Volume2,
    VolumeX,
    Watch,
    Wifi,
    WifiOff,
    Wind,
    X,
    XCircle,
    XOctagon,
    XSquare,
    Zap,
    ZapOff,
    ZoomIn,
    ZoomOut,
    Trees
} from 'lucide-react';

interface CategoryIconProps {
    iconName: string;
    size?: number;
    className?: string;
    variant?: 'default' | 'badge';
    color?: string; // Optional override color for badge background
}

const CategoryIcon: React.FC<CategoryIconProps> = ({
    iconName,
    size = 24,
    className = '',
    variant = 'default',
    color
}) => {
    // Normalize the icon name
    const normalizedName = iconName?.toLowerCase().trim() || 'default';

    // Map of icon names to Lucide components
    const iconMap: Record<string, React.ElementType> = {
        'road': Map,
        'lightbulb': Lightbulb,
        'trash': Trash2,
        'tree': Trees,
        'trees': Trees,
        'sign': MapPin, // Or better alternative if available
        'bench': Armchair,
        'help-circle': HelpCircle,
        'construction': HardHat,
        'infrastructure': Building,
        'environment': Trees,
        'public safety': Shield,
        'transportation': Bus,
        'utilities': Zap,
        'water': Droplet,
        'health': Activity,
        'education': Book,
        'housing': Home,
        'social': Users,
        'finance': DollarSign,
        'technology': Monitor,
        'culture': Music,
        'sports': Activity,
        'other': Grid,
        'autre': Grid, // Handle French "Other"
        'default': Layout,
        // Emoji mappings for backward compatibility
        '🏗️': Building,
        '🌳': Trees,
        '🔦': Search, // Flashlight not in all sets, Search or Lightbulb?
        '🚌': Bus,
        '💡': Lightbulb,
        '🚧': HardHat,
        '🗑️': Trash2,
        '🚰': Droplet,
        '⚡': Zap,
        '🏥': Activity,
        '📋': Clipboard,
    };

    // Try to find a matching icon
    // 1. Direct match
    // 2. Fallback to default
    const IconComponent = iconMap[normalizedName] || iconMap['default'];

    if (variant === 'badge') {
        return (
            <div
                className={`flex items-center justify-center rounded-full shadow-lg ${className}`}
                style={{
                    width: size * 2,
                    height: size * 2,
                    background: color || 'linear-gradient(135deg, #0D7377 0%, #32936F 100%)', // Default primary gradient
                }}
            >
                <IconComponent size={size} className="text-white drop-shadow-md" />
            </div>
        );
    }

    return <IconComponent size={size} className={className} />;
};

export default CategoryIcon;
